In [12]:
import os
import numpy as np, scipy.stats
import pandas as pd

import pyrebase
from time import sleep

In [4]:
from sklearn.externals import joblib
clf = joblib.load('model.pkl')
config = {
     "apiKey": "AIzaSyDNthbeIvXGp5AkpiHA2yMmH5SJ8ww75CQ",
     "authDomain": "lien-1553715274263.firebaseapp.com",
     "databaseURL": "https://lien-1553715274263.firebaseio.com",
     "storageBucket": "lien-1553715274263.appspot.com"
 }

firebase = pyrebase.initialize_app(config)
fb_database = firebase.database()

stored_data = fb_database.child('car_data').get().val()

In [22]:
while(1):
    z_gyro = []
    stored_data = fb_database.child('car_data').get().val()
    for key, value in stored_data.items():
        if(len(value)<11):
            continue
        z_gyro.append(value['gyro_z'])
        mean_gyro = [value['gyro_z']]
    z_gyro  =  np.diff(z_gyro[-6:],n=1)

    x_test = []
    temp_data = z_gyro
    i = 0
    x_test.append([np.amin(temp_data),np.amax(temp_data),np.ptp(temp_data),
                   np.percentile(temp_data,75),np.percentile(temp_data,25),
                   np.median(temp_data),np.mean(temp_data),np.std(temp_data),
                   np.var(temp_data),scipy.stats.kurtosis(temp_data),scipy.stats.skew(temp_data)])
    rash_percentage = clf.predict_proba(x_test)
    print(rash_percentage)
    fb_database.child('rash_drive').set({'percent': rash_percentage[0][0]})
    sleep(1)

[[0.88374079 0.11625921]]
[[0.91335587 0.08664413]]
[[0.75883408 0.24116592]]
[[0.22945369 0.77054631]]
[[0.22910145 0.77089855]]
[[0.29005833 0.70994167]]
[[0.92319435 0.07680565]]
[[0.79961109 0.20038891]]
[[0.92020301 0.07979699]]
[[0.92020301 0.07979699]]
[[0.88790373 0.11209627]]
[[0.88790373 0.11209627]]


KeyboardInterrupt: 